/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppGGroupIdRouteImport } from './routes/_app.g.$groupId'
import { Route as AppGroupsIndexRouteImport } from './routes/_app.groups.index'
import { Route as AppGroupsNewRouteImport } from './routes/_app.groups.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppGGroupIdRoute = AppGGroupIdRouteImport.update({
  id: '/g/$groupId',
  path: '/g/$groupId',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupsIndexRoute = AppGroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupsNewRoute = AppGroupsNewRouteImport.update({
  id: '/groups/new',
  path: '/groups/new',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/g/$groupId': typeof AppGGroupIdRoute
  '/groups/new': typeof AppGroupsNewRoute
  '/groups/': typeof AppGroupsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/g/$groupId': typeof AppGGroupIdRoute
  '/groups/new': typeof AppGroupsNewRoute
  '/groups': typeof AppGroupsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/g/$groupId': typeof AppGGroupIdRoute
  '/_app/groups/new': typeof AppGroupsNewRoute
  '/_app/groups/': typeof AppGroupsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/g/$groupId' | '/groups/new' | '/groups/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/g/$groupId' | '/groups/new' | '/groups'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/g/$groupId'
    | '/_app/groups/new'
    | '/_app/groups/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/g/$groupId': {
      id: '/_app/g/$groupId'
      path: '/g/$groupId'
      fullPath: '/g/$groupId'
      preLoaderRoute: typeof AppGGroupIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groups/': {
      id: '/_app/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof AppGroupsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groups/new': {
      id: '/_app/groups/new'
      path: '/groups/new'
      fullPath: '/groups/new'
      preLoaderRoute: typeof AppGroupsNewRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppGGroupIdRoute: typeof AppGGroupIdRoute
  AppGroupsNewRoute: typeof AppGroupsNewRoute
  AppGroupsIndexRoute: typeof AppGroupsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppGGroupIdRoute: AppGGroupIdRoute,
  AppGroupsNewRoute: AppGroupsNewRoute,
  AppGroupsIndexRoute: AppGroupsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
