/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ManifestDotwebmanifestRouteImport } from './routes/manifest[.]webmanifest'
import { Route as AppLoginRouteImport } from './routes/_app.login'
import { Route as AppGGroupIdRouteImport } from './routes/_app.g.$groupId'
import { Route as AppGroupsIndexRouteImport } from './routes/_app.groups.index'
import { Route as AppGroupsNewRouteImport } from './routes/_app.groups.new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestDotwebmanifestRoute = ManifestDotwebmanifestRouteImport.update({
  id: '/manifest.webmanifest',
  path: '/manifest.webmanifest',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AppRoute,
} as any)
const AppGGroupIdRoute = AppGGroupIdRouteImport.update({
  id: '/g/$groupId',
  path: '/g/$groupId',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupsIndexRoute = AppGroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupsNewRoute = AppGroupsNewRouteImport.update({
  id: '/groups/new',
  path: '/groups/new',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/login': typeof AppLoginRoute
  '/g/$groupId': typeof AppGGroupIdRoute
  '/groups/new': typeof AppGroupsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/groups/': typeof AppGroupsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/login': typeof AppLoginRoute
  '/g/$groupId': typeof AppGGroupIdRoute
  '/groups/new': typeof AppGroupsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/groups': typeof AppGroupsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/_app/login': typeof AppLoginRoute
  '/_app/g/$groupId': typeof AppGGroupIdRoute
  '/_app/groups/new': typeof AppGroupsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/groups/': typeof AppGroupsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/manifest.webmanifest'
    | '/login'
    | '/g/$groupId'
    | '/groups/new'
    | '/api/auth/$'
    | '/groups/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/manifest.webmanifest'
    | '/login'
    | '/g/$groupId'
    | '/groups/new'
    | '/api/auth/$'
    | '/groups'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/manifest.webmanifest'
    | '/_app/login'
    | '/_app/g/$groupId'
    | '/_app/groups/new'
    | '/api/auth/$'
    | '/_app/groups/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ManifestDotwebmanifestRoute: typeof ManifestDotwebmanifestRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest.webmanifest': {
      id: '/manifest.webmanifest'
      path: '/manifest.webmanifest'
      fullPath: '/manifest.webmanifest'
      preLoaderRoute: typeof ManifestDotwebmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/login': {
      id: '/_app/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/g/$groupId': {
      id: '/_app/g/$groupId'
      path: '/g/$groupId'
      fullPath: '/g/$groupId'
      preLoaderRoute: typeof AppGGroupIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groups/': {
      id: '/_app/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof AppGroupsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groups/new': {
      id: '/_app/groups/new'
      path: '/groups/new'
      fullPath: '/groups/new'
      preLoaderRoute: typeof AppGroupsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppLoginRoute: typeof AppLoginRoute
  AppGGroupIdRoute: typeof AppGGroupIdRoute
  AppGroupsNewRoute: typeof AppGroupsNewRoute
  AppGroupsIndexRoute: typeof AppGroupsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppLoginRoute: AppLoginRoute,
  AppGGroupIdRoute: AppGGroupIdRoute,
  AppGroupsNewRoute: AppGroupsNewRoute,
  AppGroupsIndexRoute: AppGroupsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ManifestDotwebmanifestRoute: ManifestDotwebmanifestRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
